# Generated by Django 5.0.1 on 2024-01-09 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Watch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watch_name', models.CharField(blank=True, max_length=100, null=True)),
                ('watch_thumbnail', models.ImageField(blank=True, null=True, upload_to='watch_thumbnails/')),
                ('brands', models.CharField(blank=True, choices=[('Amazfit', 'Amazfit'), ('Anne Klein', 'Anne Klein'), ('Armani Exchange', 'Armani Exchange'), ('Calvin Klein', 'Calvin Klein'), ('Casio', 'Casio'), ('Coach', 'Coach'), ('Daniel Wellington', 'Daniel Wellington'), ('Diesel', 'Diesel'), ('Emporio Armani', 'Emporio Armani'), ('Fitbit', 'Fitbit'), ('Fossil', 'Fossil'), ('Fossil Smartwatch', 'Fossil Smartwatch'), ('G-Shock', 'G-Shock'), ('GC', 'GC'), ('Guess', 'Guess'), ('Hugo Boss', 'Hugo Boss'), ('Kenneth Cole', 'Kenneth Cole'), ('Michael Kors', 'Michael Kors'), ('Movado', 'Movado'), ('Obaku', 'Obaku'), ('Olivia Burton', 'Olivia Burton'), ('Police', 'Police'), ('Skagen', 'Skagen'), ('Titan', 'Titan'), ('Titan Smart', 'Titan Smart'), ('Tommy Hilfiger', 'Tommy Hilfiger'), ('Versace', 'Versace'), ('Xylys', 'Xylys')], max_length=30, null=True)),
                ('watch_details', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('discount', models.IntegerField(blank=True, default=0, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Men', 'Men'), ('Unisex', 'Unisex'), ('Women', 'Women')], max_length=10, null=True)),
                ('dial_type', models.CharField(blank=True, choices=[('Analog', 'Analog'), ('Analog & Digital', 'Analog & Digital'), ('Digital', 'Digital'), ('Roman', 'Roman'), ('Smart', 'Smart')], max_length=20, null=True)),
                ('dial_colour', models.CharField(blank=True, choices=[('Black', 'Black'), ('Blue', 'Blue'), ('Gold', 'Gold'), ('Pink', 'Pink'), ('White', 'White')], max_length=20, null=True)),
                ('dial_shape', models.CharField(blank=True, choices=[('Octagonal', 'Octagonal'), ('Oval', 'Oval'), ('Polygon', 'Polygon'), ('Rectangle', 'Rectangle'), ('Rectangular', 'Rectangular'), ('Round', 'Round'), ('Square', 'Square'), ('Tonneau', 'Tonneau'), ('Triangle', 'Triangle')], max_length=20, null=True)),
                ('style', models.CharField(blank=True, choices=[('Adventure', 'Adventure'), ('Bling', 'Bling'), ('Casual', 'Casual'), ('Dressy', 'Dressy'), ('Fashion', 'Fashion'), ('Fitness', 'Fitness'), ('Formal', 'Formal'), ('Minimalistic', 'Minimalistic'), ('Party', 'Party'), ('Sporty', 'Sporty')], max_length=20, null=True)),
                ('strap_material', models.CharField(blank=True, choices=[('Acetate', 'Acetate'), ('Alloy', 'Alloy'), ('Ceramic', 'Ceramic'), ('Fabric', 'Fabric'), ('Gold', 'Gold'), ('Leather', 'Leather'), ('Metal', 'Metal'), ('Nylon', 'Nylon'), ('PU', 'PU'), ('Plastic', 'Plastic'), ('Polyurethane', 'Polyurethane'), ('Polyvinyl Chloride', 'Polyvinyl Chloride'), ('Pvc', 'Pvc'), ('Resin', 'Resin'), ('Rubber', 'Rubber'), ('Silicon', 'Silicon'), ('Silicone', 'Silicone'), ('Stainless Steel', 'Stainless Steel'), ('Stainless Steel & Ceramic', 'Stainless Steel & Ceramic'), ('Stainless Steel Mesh Band', 'Stainless Steel Mesh Band'), ('Textile', 'Textile'), ('mesh', 'Mesh')], max_length=30, null=True)),
            ],
        ),
    ]
