# Generated by Django 5.0.1 on 2024-02-03 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Watch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watch_name', models.CharField(blank=True, max_length=100, null=True)),
                ('watch_thumbnail', models.ImageField(blank=True, null=True, upload_to='watch_thumbnails/')),
                ('brands', models.CharField(blank=True, choices=[('Armani Exchange', 'Armani Exchange'), ('Calvin Klein', 'Calvin Klein'), ('Casio', 'Casio'), ('Fossil', 'Fossil'), ('G-Shock', 'G-Shock'), ('Hugo Boss', 'Hugo Boss'), ('Kenneth Cole', 'Kenneth Cole'), ('Movado', 'Movado'), ('Obaku', 'Obaku'), ('Police', 'Police'), ('Titan', 'Titan'), ('Tommy Hilfiger', 'Tommy Hilfiger')], max_length=30, null=True)),
                ('watch_details', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('discount', models.IntegerField(blank=True, default=0, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Men', 'Men'), ('Unisex', 'Unisex'), ('Women', 'Women')], max_length=10, null=True)),
                ('dial_type', models.CharField(blank=True, choices=[('Analog', 'Analog'), ('Digital', 'Digital'), ('Roman', 'Roman'), ('Smart', 'Smart')], max_length=20, null=True)),
                ('dial_colour', models.CharField(blank=True, choices=[('Black', 'Black'), ('Blue', 'Blue'), ('Gold', 'Gold'), ('Pink', 'Pink'), ('White', 'White')], max_length=20, null=True)),
                ('dial_shape', models.CharField(blank=True, choices=[('Oval', 'Oval'), ('Polygon', 'Polygon'), ('Rectangle', 'Rectangle'), ('Rectangular', 'Rectangular'), ('Round', 'Round'), ('Square', 'Square'), ('Triangle', 'Triangle')], max_length=20, null=True)),
                ('style', models.CharField(blank=True, choices=[('Adventure', 'Adventure'), ('Bling', 'Bling'), ('Casual', 'Casual'), ('Dressy', 'Dressy'), ('Fashion', 'Fashion'), ('Fitness', 'Fitness'), ('Formal', 'Formal'), ('Minimalistic', 'Minimalistic'), ('Party', 'Party'), ('Sporty', 'Sporty')], max_length=20, null=True)),
                ('strap_material', models.CharField(blank=True, choices=[('Acetate', 'Acetate'), ('Alloy', 'Alloy'), ('Ceramic', 'Ceramic'), ('Fabric', 'Fabric'), ('Gold', 'Gold'), ('Leather', 'Leather'), ('Metal', 'Metal'), ('Nylon', 'Nylon'), ('PU', 'PU'), ('Plastic', 'Plastic'), ('Rubber', 'Rubber'), ('Silicon', 'Silicon'), ('Textile', 'Textile')], max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WatchImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watch_image', models.ImageField(blank=True, null=True, upload_to='watch_image/')),
                ('watch_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.watch')),
            ],
        ),
    ]
