# Generated by Django 5.0.1 on 2024-01-17 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watch',
            name='brands',
            field=models.CharField(blank=True, choices=[('Armani Exchange', 'Armani Exchange'), ('Calvin Klein', 'Calvin Klein'), ('Casio', 'Casio'), ('Fossil', 'Fossil'), ('G-Shock', 'G-Shock'), ('Hugo Boss', 'Hugo Boss'), ('Kenneth Cole', 'Kenneth Cole'), ('Movado', 'Movado'), ('Obaku', 'Obaku'), ('Police', 'Police'), ('Titan', 'Titan'), ('Tommy Hilfiger', 'Tommy Hilfiger')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='watch',
            name='dial_shape',
            field=models.CharField(blank=True, choices=[('Oval', 'Oval'), ('Polygon', 'Polygon'), ('Rectangle', 'Rectangle'), ('Rectangular', 'Rectangular'), ('Round', 'Round'), ('Square', 'Square'), ('Triangle', 'Triangle')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='watch',
            name='dial_type',
            field=models.CharField(blank=True, choices=[('Analog', 'Analog'), ('Digital', 'Digital'), ('Roman', 'Roman'), ('Smart', 'Smart')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='watch',
            name='strap_material',
            field=models.CharField(blank=True, choices=[('Acetate', 'Acetate'), ('Alloy', 'Alloy'), ('Ceramic', 'Ceramic'), ('Fabric', 'Fabric'), ('Gold', 'Gold'), ('Leather', 'Leather'), ('Metal', 'Metal'), ('Nylon', 'Nylon'), ('PU', 'PU'), ('Plastic', 'Plastic'), ('Rubber', 'Rubber'), ('Silicon', 'Silicon'), ('Textile', 'Textile')], max_length=30, null=True),
        ),
    ]
