# Generated by Django 5.0.1 on 2024-01-29 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_orderplaced'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplaced',
            name='ordered_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
