# Generated by Django 5.0.1 on 2024-01-31 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_wishlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watch_image', models.ImageField(blank=True, null=True, upload_to='watch_image/')),
                ('watch_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.watch')),
            ],
        ),
    ]
