# Generated by Django 5.0.1 on 2024-02-05 05:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_watchimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cart',
            name='watch_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.watch'),
        ),
        migrations.AlterField(
            model_name='watchimage',
            name='watch_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.watch'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='watch_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.watch'),
        ),
    ]
